'''Create a program that will play the “cows and bulls” game with the user.The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number.
For every digit that the user guessed correctly in the correct place, they have a “cow”.
For every digit the user guessed correctly in the wrong place is a “bull.”
Every time the user makes a guess, tell them how many “cows” and “bulls” they have.
Once the user guesses the correct number, the game is over. Keep track of the number of guesses the
user makes throughout teh game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1256
  1 cow, 1 bull
  ...
Until the user guesses the number.'''

if __name__=="__main__": #main statement
    import random

    def generate_number(): #Generates random four digit integer
        x = random.randint(1000, 9999)
        y = str(x)
        x = list(str(x))
        return x, y #returns the integer as a list and as a string
    
    def is_four_digit(a): #Determine if input is a four digit number. Takes a string, returns a list
        if a.isdigit() == True:
            x = list(a)
            if len(x) == 4: #If four digit integer, return the integer
                return x
            else:
                return False #If not a four digit integer, return False
        else:
            return False #If not a digit, return False
        
    def take_input(a): #Get a four digit number from the user
        while True: #Loop request for a number until we get 4 digit or user quits
            if a == 1: #First guess
                print('>>> Welcome to the Cows and Bulls Game! <<<')
                print('I have chosen a four digit number, and it\'s your turn to guess it!')
                x = input('Enter a four digit number, or type \'quit\' to exit:')
            else: #Guess again
                x = input('Guess again! Enter a four digit number, or type \'quit\' to exit:')
            if x == 'quit': #Check if user quit before we do anything else
                return x
            y = is_four_digit(x)
            if y == False:
                print('That\'s not a valid four digit number.')
            else: #y == True then return the list
                return y
            
                
                
    def cows_bulls_count(a, b): #a = user_input, b = random_number
        cows = 0
        bulls = 0
        for x in range(len(a)):
            if a[x] == b[x]: #If a and b have same value at index slot x, then increment cows
                cows = cows + 1
            elif a[x] in b and a[x] != b[x]: #If value in a at index slot x is in b and a & b do not have the same value at index slot x
                for y in range(len(a)):
                    if a[x] == b[y]: #Look through each index slot of b for value at a's index slot x
                        bulls = bulls + 1
        print('Cows:', cows, 'Bulls:', bulls)
        return cows
            

    '''Main'''
    random_number, n = generate_number() #returns a list and the number to be guessed
    guesses = 1 #Player starts at first guess
    while True:
        user_input = take_input(guesses) #take_input returns a list
        if user_input == 'quit': #Break loop if the user typed 'quit'
            break
        result = cows_bulls_count(user_input, random_number) #Determines cows and bulls. Result is number of cows
        if result == 4: #If cows = 4, then player wins
            print('You guessed correctly! It only took', guesses, 'guesses. The number was:', n) #end
            break #End loop
        guesses = guesses + 1 #Keep track of number of guesses
            
        
        
        
    
    



